=== abdallah-samir96/OCP_17_Java_Practices/src/xml/employment.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.abdallah.com"
        xmlns = "http://www.abdallah.com"
        elementFormDefault="qualified"
>
    <xs:element name="library">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="pages" type="xs:integer"/>
                            <xs:element name="author" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="location" type="xs:string"/>
            <xs:attribute name="code" type="xs:string"/>
        </xs:complexType>


    </xs:element>

</xs:schema>

=== abdallah-samir96/OCP_17_Java_Practices/src/xml/employment.xml
<?xml version="1.0" encoding="UTF-8" ?>

<library
        xmlns="http://www.abdallah.com"
        xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation = "http://www.abdallah.com employment.xsd"
        location="cairo-egypt"
        code="74747"
>

    <book>
        <title>introduction to c++</title>
        <pages>2000</pages>
        <author>Bjarne Stroustrup</author>
    </book>

    <book>
        <title>Java programing</title>
        <pages>5000</pages>
        <author>James Gosling</author>
    </book>

    <book>
        <title>Introduction to network</title>
        <pages>400</pages>
        <author>Simple name</author>
    </book>

</library>
