=== abdallah-samir96/OCP_17_Java_Practices/src/xml/library.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.abdallah.com"
        xmlns = "http://www.abdallah.com"
        elementFormDefault="qualified"
>
<!--    unqualified that mean you should use the xml document without namespace, without xsd file so you must add it as qualified-->
    <xs:element name="library">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="pages" type="xs:integer"/>
                        <xs:element name="author" type="xs:string"/>
                        <xs:element name="type" type="category"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            </xs:sequence>
            <xs:attribute name="location" type="xs:string"/>
            <xs:attribute name="code" type="xs:string"/>
        </xs:complexType>


    </xs:element>
    <xs:simpleType name="category">
        <xs:restriction>
            <xs:enumeration value="COMPUTER_SCIENCE" />
            <xs:enumeration value="HISTORY" />
            <xs:enumeration value="OTHERS" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="anything">
        <xs:list itemType="xs:integer" />
    </xs:simpleType>

</xs:schema>

=== abdallah-samir96/OCP_17_Java_Practices/src/xml/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--we removed    those elements because the xslt will read it
xmlns="http://www.abdallah.com"
        xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation = "http://www.abdallah.com library.xsd"
        -->
<library

>
    <book>
        <title>introduction to c++</title>
        <pages>2000</pages>
        <author>Bjarne Stroustrup</author>
        <type>COMPUTER_SCIENCE</type>
    </book>

    <book>
        <title>Java programing</title>
        <pages>5000</pages>
        <author>James Gosling</author>
        <type>COMPUTER_SCIENCE</type>
    </book>

    <book>
        <title>Introduction to network</title>
        <pages>400</pages>
        <author>Any one</author>
        <type>COMPUTER_SCIENCE</type>
    </book>

</library>
